profiles:
  development:
    cook: microwave
  production:
    cook: oven
    asciidoctor:
      :eruby: erb
      :attributes:
        imagesdir: /img
  staging:
    compass_line_comments: off

title: Awestruction!

asciidoctor:
  :safe: 0
  :eruby: erubis
  :attributes:
    imagesdir: /assets/images
    idprefix: ''
